version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres:15-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./conf/env_variables/.env
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=drunkenmaster1.
      - POSTGRES_DB=testdb
    restart: "always"

  app:
    container_name: starter_app
    build: .
    #command: ./conf/scripts/local/provide_env.sh
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./conf/env_variables/.env
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: "always"

# volumes:
#   postgres_data: